#!/usr/bin/env bash

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Get the server's hostname
hostname=$(hostname)

# Create an Nginx config file to add the custom header
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header X-Served-By $hostname;

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
systemctl reload nginx
