#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Configure custom HTTP response header
sudo sed -i '/http {/a \        server_tokens off;\n        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx